#Start : This will build the image and push it to container registry.
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Clone Env repository
    entrypoint: /bin/sh
    args:
     - '-c'
     - |
       git clone https://github.com/sharma-dilip/GCP-EnvironmentRepo.git && \
       cd GCP-EnvironmentRepo && \
       git checkout test-branch
# This step generates the new manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Generate kubernetes manifest
    entrypoint: /bin/sh
    args:
     - '-c'
     - |
       git remote -v
       sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yaml.tpl | \
       sed "s/COMMIT_SHA/${REVISION_ID}/g" > GCP-EnvironmentRepo/kubernetes.yaml
