#Start : This will build the image and push it to container registry.
steps:
#  - name: 'gcr.io/cloud-builders/npm'  
#    args: ['install']
  - name: 'gcr.io/cloud-builders/npm:latest'
    args: ['--version']
  - name: 'gcr.io/cloud-builders/npm:latest'  
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'  
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-image:$REVISION_ID", "."]
  - name: 'gcr.io/cloud-builders/docker'  
    args: ["push", "gcr.io/$PROJECT_ID/my-image:$REVISION_ID"]
#End : This will build the image and push it to container registry.
#This will clone the environment repository
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Clone Env repository
    entrypoint: /bin/sh
    args:
     - '-c'
     - |
       git clone git@github.com:sharma-dilip/GCP-EnvironmentRepo.git  && \
       cd GCP-EnvironmentRepo && \
       git checkout test-branch && \
#      git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
