#Start : This will build the image and push it to container registry.
steps:
#  - name: 'gcr.io/cloud-builders/npm'  
#    args: ['install']
  - name: 'gcr.io/cloud-builders/npm:latest'
    args: ['--version']
  - name: 'gcr.io/cloud-builders/npm:latest'  
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'  
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-image:$REVISION_ID", "."]
  - name: 'gcr.io/cloud-builders/docker'  
    args: ["push", "gcr.io/$PROJECT_ID/my-image:$REVISION_ID"]
#End : This will build the image and push it to container registry.
#This will connect to the environment repository
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Connect to the Repository
    entrypoint: /bin/sh
    args:
     - '-c'
     - |
       ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
       git clone git@github.com:sharma-dilip/GCP-EnvironmentRepo.git && \
    volumes:
    - name: 'ssh'
      path: /root/.ssh
# This step to clone the repo and switch to it
  - name: 'gcr.io/cloud-builders/gcloud'
    id: To Clone the repo and switch to it
    dir: GCP-EnvironmentRepo    
    entrypoint: /bin/sh
    args:
     - '-c'
     - |
       set -x && \
       git config --global user.email "sha.dilip87@gmail.com"
       git config --global user.name "sharma-dilip"
       git fetch origin test-branch && git switch test-branch
    volumes:
    - name: 'ssh'
      path: /root/.ssh
# This step generates the new manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Generate kubernetes manifests
    dir: GCP-EnvironmentRepo
    entrypoint: /bin/sh
    args:
     - '-c'
     - |
       set -x && \
       sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yaml.tpl | \
       sed "s/COMMIT_SHA/${REVISION_ID}/g" > kubernetes.yaml
# This step pushes the manifest back to GCP-EnvironmentRepo
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Push manifest
    dir: GCP-EnvironmentRepo
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      set -x && \
      git add kubernetes.yaml && \
      git commit -m "Deploying image gcr.io/${PROJECT_ID}/my-image:${REVISION_ID}" && \
      git push origin test-branch
    volumes:
    - name: 'ssh'
      path: /root/.ssh      
      
