#This will connect to the environment repository
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Connect to the Repository
    entrypoint: /bin/sh
    args:
     - '-c'
     - |
       ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
       git clone git@github.com:sharma-dilip/GCP-EnvironmentRepo.git
    volumes:
    - name: 'ssh'
      path: /root/.ssh
